// <auto-generated />
using System;
using Groove.CSFE.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Groove.CSFE.Persistence.Migrations
{
    [DbContext(typeof(CsfeContext))]
    [Migration("20220526102309_Update_Schema_EmailNotificationModel_Add_FK")]
    partial class Update_Schema_EmailNotificationModel_Add_FK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Groove.CSFE.Core.Entities.AlternativeLocationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("LocationId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("AlternativeLocations");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.CarrierModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarrierCode")
                        .HasColumnType("NVARCHAR(128)");

                    b.Property<int?>("CarrierNumber");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("ModeOfTransport")
                        .HasColumnType("NVARCHAR(128)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.CountryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.CurrencyModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<byte?>("CurrencyPrecision")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("DECIMAL(18, 4)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.CustomerRelationshipModel", b =>
                {
                    b.Property<long>("SupplierId");

                    b.Property<long>("CustomerId");

                    b.Property<int>("ConnectionType");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CustomerRefId")
                        .HasColumnType("NVARCHAR(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("IsConfirmConnectionType");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("SupplierId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerRelationship");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.EmailNotificationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CountryId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("CustomerId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<long>("OrganizationId");

                    b.Property<string>("PortSelectionIds");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("EmailNotifications");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.EventCodeModel", b =>
                {
                    b.Property<string>("ActivityCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(512)")
                        .HasMaxLength(512);

                    b.Property<string>("ActivityTypeCode")
                        .HasColumnType("NVARCHAR(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("LocationRequired");

                    b.Property<bool>("RemarkRequired");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("SortSequence");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("ActivityCode");

                    b.HasIndex("ActivityTypeCode");

                    b.ToTable("EventCodes");

                    b.HasData(
                        new
                        {
                            ActivityCode = "1000",
                            ActivityDescription = "PO Issued",
                            ActivityTypeCode = "PM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1001",
                            ActivityDescription = "PO on hold",
                            ActivityTypeCode = "PE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1002",
                            ActivityDescription = "PO Acknowledged",
                            ActivityTypeCode = "PA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1003",
                            ActivityDescription = "PO Amendment",
                            ActivityTypeCode = "PA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1004",
                            ActivityDescription = "PO Amendment Failure",
                            ActivityTypeCode = "PE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1005",
                            ActivityDescription = "PO cancelled",
                            ActivityTypeCode = "PE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1006",
                            ActivityDescription = "PO Cancellation Failure",
                            ActivityTypeCode = "PA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1010",
                            ActivityDescription = "PO Closed",
                            ActivityTypeCode = "PM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1011",
                            ActivityDescription = "PO Reopen",
                            ActivityTypeCode = "PA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1013",
                            ActivityDescription = "Progress Check",
                            ActivityTypeCode = "PA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1050",
                            ActivityDescription = "Booking Planning",
                            ActivityTypeCode = "FM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1051",
                            ActivityDescription = "Booked",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1052",
                            ActivityDescription = "Booking Itinerary Ready",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1053",
                            ActivityDescription = "Booking Accepted",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1054",
                            ActivityDescription = "Booking Denied",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1055",
                            ActivityDescription = "Booking Approval Request",
                            ActivityTypeCode = "FE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1056",
                            ActivityDescription = "Booking Amended",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1057",
                            ActivityDescription = "Booking Cancelled",
                            ActivityTypeCode = "FE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1058",
                            ActivityDescription = "Booking Approved",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1059",
                            ActivityDescription = "Booking Rejected",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1060",
                            ActivityDescription = "Booking Approval Overdue",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1061",
                            ActivityDescription = "PO Booking confirmed",
                            ActivityTypeCode = "FM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1062",
                            ActivityDescription = "Plan to ship",
                            ActivityTypeCode = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1063",
                            ActivityDescription = "Cargo Received",
                            ActivityTypeCode = "FM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1069",
                            ActivityDescription = "Shipment Amendment",
                            ActivityTypeCode = "FE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1070",
                            ActivityDescription = "Shipment Cancellation",
                            ActivityTypeCode = "FE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1071",
                            ActivityDescription = "Booking Closed",
                            ActivityTypeCode = "FM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1072",
                            ActivityDescription = "Reopen Booking",
                            ActivityTypeCode = "FE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1073",
                            ActivityDescription = "Booking Completed",
                            ActivityTypeCode = "FM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "1074",
                            ActivityDescription = "SO Released Date",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2000",
                            ActivityDescription = "Booking received",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2001",
                            ActivityDescription = "Booking on hold",
                            ActivityTypeCode = "SE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2005",
                            ActivityDescription = "Booking confirmed",
                            ActivityTypeCode = "SM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2006",
                            ActivityDescription = "Container(s) released to shipper",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2009",
                            ActivityDescription = "Partial handover in origin CFS",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2011",
                            ActivityDescription = "Non-conformance cargo found",
                            ActivityTypeCode = "SE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2012",
                            ActivityDescription = "Pulled for inspection",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2014",
                            ActivityDescription = "Cargo handover at origin",
                            ActivityTypeCode = "SM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2015",
                            ActivityDescription = "Shipment booked with carrier",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2016",
                            ActivityDescription = "Shipment rejected by carrier",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2017",
                            ActivityDescription = "Shipment re-book with alternative carrier/schedule",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2021",
                            ActivityDescription = "Shipment pending for shipper document",
                            ActivityTypeCode = "SE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2026",
                            ActivityDescription = "Shipment export customs hold",
                            ActivityTypeCode = "SE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2027",
                            ActivityDescription = "Shipment export cleared",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2028",
                            ActivityDescription = "Shipment late departure alert",
                            ActivityTypeCode = "SE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2034",
                            ActivityDescription = "Bill of Lading released to Shipper",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2040",
                            ActivityDescription = "Shipment import customs hold",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2041",
                            ActivityDescription = "Shipment import customs cleared",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2043",
                            ActivityDescription = "BOL surrendered received at destination",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2053",
                            ActivityDescription = "Appointment made with consignee",
                            ActivityTypeCode = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "2054",
                            ActivityDescription = "Shipment handover to consignee",
                            ActivityTypeCode = "SM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3000",
                            ActivityDescription = "Container - Empty Pickup",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3001",
                            ActivityDescription = "Container - Gate In",
                            ActivityTypeCode = "CM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3002",
                            ActivityDescription = "Container - Vessel Load",
                            ActivityTypeCode = "CM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3005",
                            ActivityDescription = "Container - Vessel Unload",
                            ActivityTypeCode = "CM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3006",
                            ActivityDescription = "Container - Gate Out",
                            ActivityTypeCode = "CM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3007",
                            ActivityDescription = "Container - Empty Return",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3016",
                            ActivityDescription = "Customs Hold (PA)",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3017",
                            ActivityDescription = "Customs Released (CT)",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3018",
                            ActivityDescription = "Carrier Hold (X9)",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3019",
                            ActivityDescription = "Carrier Release (CR)",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3031",
                            ActivityDescription = "Free Demurrage Ends",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3032",
                            ActivityDescription = "Free Detention Ends",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3033",
                            ActivityDescription = "Haulage to Offdock CY",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3034",
                            ActivityDescription = "Receipt of Containers at Offdock CY",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3050",
                            ActivityDescription = "CFS Closing Date",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3051",
                            ActivityDescription = "CY Closing Date",
                            ActivityTypeCode = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3098",
                            ActivityDescription = "Demurrage Alert",
                            ActivityTypeCode = "CE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "3099",
                            ActivityDescription = "Detention Alert",
                            ActivityTypeCode = "CE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "4000",
                            ActivityDescription = "Shipment Completed",
                            ActivityTypeCode = "ES",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "4001",
                            ActivityDescription = "Shipment Abandoned",
                            ActivityTypeCode = "EE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = true,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5000",
                            ActivityDescription = "PICK- Pick up arranged for loose cargo",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5001",
                            ActivityDescription = "ON HAND- Goods received in hub",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5002",
                            ActivityDescription = "ATS- Authorized To Ship",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5003",
                            ActivityDescription = "VC- Booked For Vendor",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5004",
                            ActivityDescription = "OG- Delivered Origin",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5005",
                            ActivityDescription = "COB- Confirm On Board",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5006",
                            ActivityDescription = "SHI- Shipped",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5007",
                            ActivityDescription = "TRN- In Transit",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5008",
                            ActivityDescription = "PT- Transhipment",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5009",
                            ActivityDescription = "AR- Arrived At Destination",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5010",
                            ActivityDescription = "DL- Delivered To Shipyard",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5011",
                            ActivityDescription = "SSD- Container To Ship",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5012",
                            ActivityDescription = "RE- Container Empty",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "5013",
                            ActivityDescription = "IG- Empty Container Returned",
                            ActivityTypeCode = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = false,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "7001",
                            ActivityDescription = "Vessel Departure",
                            ActivityTypeCode = "VA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "7002",
                            ActivityDescription = "Vessel Arrival",
                            ActivityTypeCode = "VA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "7003",
                            ActivityDescription = "Flight Departure",
                            ActivityTypeCode = "VA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        },
                        new
                        {
                            ActivityCode = "7004",
                            ActivityDescription = "Flight Arrival",
                            ActivityTypeCode = "VA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2021, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationRequired = true,
                            RemarkRequired = false,
                            SortSequence = 0L
                        });
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.EventTypeModel", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(512)")
                        .HasMaxLength(512);

                    b.Property<int>("EventLevel");

                    b.Property<string>("LevelDescription")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Code");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Code = "PM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Purchase Order Milestone Event",
                            EventLevel = 1,
                            LevelDescription = "PO"
                        },
                        new
                        {
                            Code = "PE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Purchase Order Exception Event",
                            EventLevel = 1,
                            LevelDescription = "PO"
                        },
                        new
                        {
                            Code = "PA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Purchase Order Activity Event",
                            EventLevel = 1,
                            LevelDescription = "PO"
                        },
                        new
                        {
                            Code = "FM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Booking Milestone Event",
                            EventLevel = 2,
                            LevelDescription = "Booking"
                        },
                        new
                        {
                            Code = "FA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Booking Activity Event",
                            EventLevel = 2,
                            LevelDescription = "Booking"
                        },
                        new
                        {
                            Code = "FE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Booking Exception Event",
                            EventLevel = 2,
                            LevelDescription = "Booking"
                        },
                        new
                        {
                            Code = "OM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shipping Order Milestone Event",
                            EventLevel = 3,
                            LevelDescription = "SO"
                        },
                        new
                        {
                            Code = "OE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shipping Order Exception Event",
                            EventLevel = 3,
                            LevelDescription = "SO"
                        },
                        new
                        {
                            Code = "OA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shipping Order Activity Event",
                            EventLevel = 3,
                            LevelDescription = "SO"
                        },
                        new
                        {
                            Code = "SE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shipment Exception Event",
                            EventLevel = 4,
                            LevelDescription = "Shipment"
                        },
                        new
                        {
                            Code = "SM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shipment Milestone Event",
                            EventLevel = 4,
                            LevelDescription = "Shipment"
                        },
                        new
                        {
                            Code = "SA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shipment Activity Event",
                            EventLevel = 4,
                            LevelDescription = "Shipment"
                        },
                        new
                        {
                            Code = "CA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Container Activity Event",
                            EventLevel = 5,
                            LevelDescription = "Container"
                        },
                        new
                        {
                            Code = "CM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Container Milestone Event",
                            EventLevel = 5,
                            LevelDescription = "Container"
                        },
                        new
                        {
                            Code = "CE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Container Exception Event",
                            EventLevel = 5,
                            LevelDescription = "Container"
                        },
                        new
                        {
                            Code = "MM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master Milestone Event",
                            EventLevel = 6,
                            LevelDescription = "Master"
                        },
                        new
                        {
                            Code = "ME",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master Exception Event",
                            EventLevel = 6,
                            LevelDescription = "Master"
                        },
                        new
                        {
                            Code = "MA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master Activity Event",
                            EventLevel = 6,
                            LevelDescription = "Master"
                        },
                        new
                        {
                            Code = "VM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vessel Milestone Event",
                            EventLevel = 7,
                            LevelDescription = "Vessel"
                        },
                        new
                        {
                            Code = "VE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vessel Exception Event",
                            EventLevel = 7,
                            LevelDescription = "Vessel"
                        },
                        new
                        {
                            Code = "VA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vessel Activity Event",
                            EventLevel = 7,
                            LevelDescription = "Vessel"
                        },
                        new
                        {
                            Code = "EP",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "End of Purchase Order",
                            EventLevel = 1,
                            LevelDescription = "End"
                        },
                        new
                        {
                            Code = "ES",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "End of Shipment",
                            EventLevel = 4,
                            LevelDescription = "End"
                        },
                        new
                        {
                            Code = "EE",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "End with Exception",
                            EventLevel = 4,
                            LevelDescription = "End"
                        },
                        new
                        {
                            Code = "CSM",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cruise Shipment Milestone",
                            EventLevel = 4,
                            LevelDescription = "Cruise"
                        });
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.LocationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CountryId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EdiSonPortCode")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.OrganizationInRoleModel", b =>
                {
                    b.Property<long>("OrganizationId");

                    b.Property<long>("OrganizationRoleId");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("OrganizationId", "OrganizationRoleId");

                    b.HasIndex("OrganizationRoleId");

                    b.ToTable("OrganizationInRoles");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.OrganizationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine4")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdminUser");

                    b.Property<int>("AgentType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CustomerPrefix")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EdisonCompanyCodeId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EdisonInstanceId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsBuyer");

                    b.Property<long?>("LocationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OrganizationLogo");

                    b.Property<int>("OrganizationType");

                    b.Property<string>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Status");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("WebsiteDomain");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("ParentId");

                    b.HasIndex("CreatedDate", "Name", "Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.OrganizationRoleModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OrganizationTypes");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("OrganizationRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shipper",
                            OrganizationTypes = 7
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consignee",
                            OrganizationTypes = 7
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Notify Party",
                            OrganizationTypes = 7
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Also Notify",
                            OrganizationTypes = 7
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Import Broker",
                            OrganizationTypes = 7
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Export Broker",
                            OrganizationTypes = 7
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Origin Agent",
                            OrganizationTypes = 2
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Destination Agent",
                            OrganizationTypes = 2
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Principal",
                            OrganizationTypes = 4
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Supplier",
                            OrganizationTypes = 4
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Delegation",
                            OrganizationTypes = 4
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Billing Party",
                            OrganizationTypes = 7
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pickup",
                            OrganizationTypes = 7
                        });
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.PortModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirportCode")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("AlternativeName")
                        .HasColumnType("NVARCHAR(512)");

                    b.Property<string>("ChineseName")
                        .HasColumnType("NVARCHAR(512)");

                    b.Property<long>("CountryId");

                    b.Property<string>("CountryName")
                        .HasColumnType("NVARCHAR(512)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsAirport");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("SeaportCode")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.VesselModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR(64)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsRealVessel")
                        .HasColumnType("BIT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Status");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.WarehouseAssignmentModel", b =>
                {
                    b.Property<long>("OrganizationId");

                    b.Property<long>("WarehouseLocationId");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("OrganizationId", "WarehouseLocationId");

                    b.HasIndex("WarehouseLocationId");

                    b.ToTable("WarehouseAssignments");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.WarehouseLocationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AddressLine4")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("LocationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("OrganizationId");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("WarehouseLocations");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.AlternativeLocationModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.LocationModel", "Location")
                        .WithMany("AlternativeLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.CustomerRelationshipModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationModel", "Supplier")
                        .WithMany("CustomerRelationship")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.EmailNotificationModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.CountryModel", "Country")
                        .WithMany("EmailNotifications")
                        .HasForeignKey("CountryId");

                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationModel", "Organization")
                        .WithMany("EmailNotifications")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.EventCodeModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.EventTypeModel", "ActivityType")
                        .WithMany("EventCodes")
                        .HasForeignKey("ActivityTypeCode");
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.LocationModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.CountryModel", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.OrganizationInRoleModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationModel", "Organization")
                        .WithMany("OrganizationInRoles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationRoleModel", "OrganizationRole")
                        .WithMany("OrganizationInRoles")
                        .HasForeignKey("OrganizationRoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.OrganizationModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.LocationModel", "Location")
                        .WithMany("Organizations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.WarehouseAssignmentModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationModel", "Organization")
                        .WithMany("WarehouseAssignments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Groove.CSFE.Core.Entities.WarehouseLocationModel", "WarehouseLocation")
                        .WithMany("WarehouseAssignments")
                        .HasForeignKey("WarehouseLocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Groove.CSFE.Core.Entities.WarehouseLocationModel", b =>
                {
                    b.HasOne("Groove.CSFE.Core.Entities.LocationModel", "Location")
                        .WithMany("WarehouseLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Groove.CSFE.Core.Entities.OrganizationModel", "Organization")
                        .WithMany("Warehouses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
